import Foundation
import XCTest
import ProverGateCore
@testable import ProverGate

/// The privacy circuits proved through Swoirenberg on this Mac, from the
/// chain's own witness fixtures (android test resources, generated by the
/// chain's tools/privacyfixtures and tools/orchardfixtures): the public inputs come back as the
/// chain's, the proof verifies, its body is the size the chain expects, and
/// the verification key is byte for byte the one seeded in genesis — the VK
/// derives from the circuit and the bb build alone, so equality is the proof
/// that this prover and the chain's verifier share one bb v5.0.0.
///
/// The proof and public inputs are written to ProverGate/.artifacts for
/// tools/chainverify (the chain's own Go verifier).
final class PrivacyProverTests: XCTestCase {
    func parseToml(_ text: String) -> [String: Any] {
        func value(_ v: Substring) -> Any {
            let s = v.trimmingCharacters(in: .whitespaces)
            guard s.hasPrefix("[") else { return s.trimmingCharacters(in: CharacterSet(charactersIn: "\"")) }
            let inner = s.dropFirst().dropLast()
            if inner.trimmingCharacters(in: .whitespaces).hasPrefix("[") {
                var parts: [Any] = [], depth = 0, start = inner.startIndex
                for i in inner.indices {
                    if inner[i] == "[" { if depth == 0 { start = i }; depth += 1 }
                    if inner[i] == "]" { depth -= 1; if depth == 0 { parts.append(value(inner[start ... i])) } }
                }
                return parts
            }
            return inner.split(separator: ",").map { $0.trimmingCharacters(in: CharacterSet(charactersIn: "\" ")) }
        }
        var out: [String: Any] = [:]
        for line in text.split(separator: "\n") where !line.hasPrefix("#") {
            guard let r = line.range(of: " = ") else { continue }
            out[String(line[..<r.lowerBound])] = value(line[r.upperBound...])
        }
        return out
    }

    func hex(_ d: Data) -> String { d.map { String(format: "%02x", $0) }.joined() }

    static func manifests(_ root: URL) throws -> [PrivacyCircuitProver.Kind: Data] {
        let circuits = root.appendingPathComponent("android/app/src/main/assets/circuits")
        var manifests: [PrivacyCircuitProver.Kind: Data] = [:]
        for k in PrivacyCircuitProver.Kind.allCases { manifests[k] = try Data(contentsOf: circuits.appendingPathComponent("\(k.rawValue).json")) }
        return manifests
    }

    /// One prover for the whole test process: bb sizes its SRS once, so the
    /// first circuit to prove must not be the smallest.
    static let shared: PrivacyCircuitProver = {
        let root = try! RepoLayout.root(from: #filePath)
        return PrivacyCircuitProver(manifests: try! manifests(root))
    }()

    /// The chain checkout beside this one, if any (privacy/orchard).
    static func genesisVK(_ root: URL, _ kind: PrivacyCircuitProver.Kind) -> Data? {
        for name in ["chain-orch", "chain-orchard", "chain-privacy", "earth-network-chain"] {
            let f = root.deletingLastPathComponent().appendingPathComponent("\(name)/networks/genesis/shielded-verifying-keys/\(kind.rawValue).vk.b64")
            if let b64 = try? String(contentsOf: f, encoding: .utf8) { return Data(base64Encoded: b64.trimmingCharacters(in: .whitespacesAndNewlines)) }
        }
        return nil
    }

    func check(_ kind: PrivacyCircuitProver.Kind, fixture name: String) throws {
        let root = try RepoLayout.root(from: #filePath)
        let fixture = root.appendingPathComponent("android/app/src/test/resources/privacy/\(name)")
        let prover = Self.shared
        let inputs = parseToml(try String(contentsOf: fixture.appendingPathComponent("Prover.toml"), encoding: .utf8))
        let expectedRaw = try Data(contentsOf: fixture.appendingPathComponent("public_inputs.expected"))
        let expected = (0 ..< expectedRaw.count / 32).map { hex(expectedRaw.subdata(in: 32 * $0 ..< 32 * $0 + 32)) }
        XCTAssertEqual(kind.publicInputs, expected.count)

        let body = try prover.prove(kind, inputs: inputs, expected: expected)
        print("\(kind.rawValue) proved in \(prover.lastMillis[kind] ?? -1)ms")
        XCTAssertEqual(PrivacyCircuitProver.proofBytes, body.count)
        XCTAssertTrue(try prover.verify(kind, body: body, publicInputs: expected))

        // The genesis VK, byte for byte.
        if let vk = Self.genesisVK(root, kind) {
            XCTAssertEqual(vk, try prover.verificationKey(kind), "\(kind.rawValue) VK differs from the chain's genesis VK")
        } else {
            print("chain checkout not beside this one; VK comparison skipped")
        }

        let out = root.appendingPathComponent("ios/ProverGate/.artifacts")
        try FileManager.default.createDirectory(at: out, withIntermediateDirectories: true)
        try hex(try prover.verificationKey(kind)).write(to: out.appendingPathComponent("\(kind.rawValue)_vk.hex"), atomically: true, encoding: .utf8)
        try hex(body).write(to: out.appendingPathComponent("\(kind.rawValue)_proof_body.hex"), atomically: true, encoding: .utf8)
        try expected.map { decimalFromHex($0) }.joined(separator: "\n")
            .write(to: out.appendingPathComponent("\(kind.rawValue)_public_signals.txt"), atomically: true, encoding: .utf8)
    }

    func testMembership() throws { try check(.membership, fixture: "fixture_membership") }
    func testAction() throws {
        for i in 0 ..< 3 { try check(.action, fixture: "fixture_action/action_\(i)") }
    }

    /// With PRIVACY_TOML_DIR set to EarthCore's dumped wallet witnesses
    /// (WalletFlowTests with PRIVACY_TOML_OUT: <dir>/{action,stake,
    /// membership}/<test>_<i>/Prover.toml), proves every one (or the first
    /// PRIVACY_TOML_LIMIT of each kind) through this prover and verifies it
    /// with the genesis-equal VK. The stake circuit has no chain fixture, so
    /// this is where a stake proof is made and checked.
    func testWalletWitnesses() throws {
        guard let dir = ProcessInfo.processInfo.environment["PRIVACY_TOML_DIR"] else { throw XCTSkip("PRIVACY_TOML_DIR not set") }
        let limit = ProcessInfo.processInfo.environment["PRIVACY_TOML_LIMIT"].flatMap(Int.init) ?? .max
        let root = try RepoLayout.root(from: #filePath)
        let prover = Self.shared
        let order: [PrivacyCircuitProver.Kind: [String]] = [
            .action: ["anchor", "nf", "cm_out", "cv_x", "cv_y", "sighash"],
            .stake: ["anchor", "asset", "nf_0", "nf_1", "cm_out_0", "cm_out_1", "v_in", "v_out", "spc_mint", "otag", "sighash"],
            .membership: ["root", "scope", "nullifier", "signal", "excluded_dsc", "excluded_country", "max_activation"],
        ]
        var proved = 0
        for kind in [PrivacyCircuitProver.Kind.stake, .action, .membership] {
            let kdir = URL(fileURLWithPath: dir).appendingPathComponent(kind.rawValue)
            let cases = ((try? FileManager.default.contentsOfDirectory(atPath: kdir.path)) ?? []).sorted().prefix(limit)
            for c in cases {
                let inputs = parseToml(try String(contentsOf: kdir.appendingPathComponent(c).appendingPathComponent("Prover.toml"), encoding: .utf8))
                // The public inputs in the chain's order, from the witness itself.
                let expected = order[kind]!.flatMap { k -> [String] in
                    let v = inputs[k]!
                    let xs = (v as? [String]) ?? [v as! String]
                    return xs.map { x in
                        let h = x.hasPrefix("0x") ? String(x.dropFirst(2)) : hexFromDecimal(x)
                        return String(repeating: "0", count: 64 - h.count) + h
                    }
                }
                XCTAssertEqual(kind.publicInputs, expected.count)
                let body = try prover.prove(kind, inputs: inputs, expected: expected)
                XCTAssertEqual(PrivacyCircuitProver.proofBytes, body.count)
                XCTAssertTrue(try prover.verify(kind, body: body, publicInputs: expected), "\(kind.rawValue)/\(c)")
                print("\(kind.rawValue)/\(c) proved in \(prover.lastMillis[kind] ?? -1)ms")
                if c == cases.first {
                    // For tools/chainverify (prefix wallet_<kind>): the stake circuit has no other Swift proof to check.
                    let out = root.appendingPathComponent("ios/ProverGate/.artifacts")
                    try FileManager.default.createDirectory(at: out, withIntermediateDirectories: true)
                    let p = "wallet_\(kind.rawValue)"
                    try hex(try prover.verificationKey(kind)).write(to: out.appendingPathComponent("\(p)_vk.hex"), atomically: true, encoding: .utf8)
                    try hex(body).write(to: out.appendingPathComponent("\(p)_proof_body.hex"), atomically: true, encoding: .utf8)
                    try expected.map { decimalFromHex($0) }.joined(separator: "\n")
                        .write(to: out.appendingPathComponent("\(p)_public_signals.txt"), atomically: true, encoding: .utf8)
                }
                proved += 1
            }
            if let vk = Self.genesisVK(root, kind) { XCTAssertEqual(vk, try prover.verificationKey(kind), "\(kind.rawValue) genesis VK") }
        }
        XCTAssertGreaterThan(proved, 0)
    }
}
