import Foundation
import XCTest
import ProverGateCore
@testable import ProverGate

/// The privacy circuits proved through Swoirenberg on this Mac, from the
/// chain's own witness fixtures (android test resources, generated by the
/// chain's tools/privacyfixtures): the public inputs come back as the
/// chain's, the proof verifies, its body is the size the chain expects, and
/// the verification key is byte for byte the one seeded in genesis — the VK
/// derives from the circuit and the bb build alone, so equality is the proof
/// that this prover and the chain's verifier share one bb v5.0.0.
///
/// The proof and public inputs are written to ProverGate/.artifacts for
/// tools/chainverify (the chain's own Go verifier).
final class PrivacyProverTests: XCTestCase {
    func parseToml(_ text: String) -> [String: Any] {
        func value(_ v: Substring) -> Any {
            let s = v.trimmingCharacters(in: .whitespaces)
            guard s.hasPrefix("[") else { return s.trimmingCharacters(in: CharacterSet(charactersIn: "\"")) }
            let inner = s.dropFirst().dropLast()
            if inner.trimmingCharacters(in: .whitespaces).hasPrefix("[") {
                var parts: [Any] = [], depth = 0, start = inner.startIndex
                for i in inner.indices {
                    if inner[i] == "[" { if depth == 0 { start = i }; depth += 1 }
                    if inner[i] == "]" { depth -= 1; if depth == 0 { parts.append(value(inner[start ... i])) } }
                }
                return parts
            }
            return inner.split(separator: ",").map { $0.trimmingCharacters(in: CharacterSet(charactersIn: "\" ")) }
        }
        var out: [String: Any] = [:]
        for line in text.split(separator: "\n") where !line.hasPrefix("#") {
            guard let r = line.range(of: " = ") else { continue }
            out[String(line[..<r.lowerBound])] = value(line[r.upperBound...])
        }
        return out
    }

    func hex(_ d: Data) -> String { d.map { String(format: "%02x", $0) }.joined() }

    func check(_ kind: PrivacyCircuitProver.Kind) throws {
        let root = try RepoLayout.root(from: #filePath)
        let circuits = root.appendingPathComponent("android/app/src/main/assets/circuits")
        let fixture = root.appendingPathComponent("android/app/src/test/resources/privacy/fixture_\(kind.rawValue)")
        var manifests: [PrivacyCircuitProver.Kind: Data] = [:]
        for k in PrivacyCircuitProver.Kind.allCases { manifests[k] = try Data(contentsOf: circuits.appendingPathComponent("\(k.rawValue).json")) }
        let prover = PrivacyCircuitProver(manifests: manifests)
        let inputs = parseToml(try String(contentsOf: fixture.appendingPathComponent("Prover.toml"), encoding: .utf8))
        let expectedRaw = try Data(contentsOf: fixture.appendingPathComponent("public_inputs.expected"))
        let expected = (0 ..< expectedRaw.count / 32).map { hex(expectedRaw.subdata(in: 32 * $0 ..< 32 * $0 + 32)) }
        XCTAssertEqual(kind.publicInputs, expected.count)

        let body = try prover.prove(kind, inputs: inputs, expected: expected)
        print("\(kind.rawValue) proved in \(prover.lastMillis[kind] ?? -1)ms")
        XCTAssertEqual(PrivacyCircuitProver.proofBytes, body.count)
        XCTAssertTrue(try prover.verify(kind, body: body, publicInputs: expected))

        // The genesis VK, byte for byte.
        let chain = root.deletingLastPathComponent().appendingPathComponent("chain-privacy/networks/genesis/shielded-verifying-keys/\(kind.rawValue).vk.b64")
        if let b64 = try? String(contentsOf: chain, encoding: .utf8) {
            XCTAssertEqual(Data(base64Encoded: b64.trimmingCharacters(in: .whitespacesAndNewlines)), try prover.verificationKey(kind),
                           "\(kind.rawValue) VK differs from the chain's genesis VK")
        } else {
            print("chain checkout not beside this one; VK comparison skipped")
        }

        let out = root.appendingPathComponent("ios/ProverGate/.artifacts")
        try FileManager.default.createDirectory(at: out, withIntermediateDirectories: true)
        try hex(try prover.verificationKey(kind)).write(to: out.appendingPathComponent("\(kind.rawValue)_vk.hex"), atomically: true, encoding: .utf8)
        try hex(body).write(to: out.appendingPathComponent("\(kind.rawValue)_proof_body.hex"), atomically: true, encoding: .utf8)
        try expected.map { decimalFromHex($0) }.joined(separator: "\n")
            .write(to: out.appendingPathComponent("\(kind.rawValue)_public_signals.txt"), atomically: true, encoding: .utf8)
    }

    func testMembership() throws { try check(.membership) }
    func testTransfer() throws { try check(.transfer) }

    /// With PRIVACY_TOML_DIR set to EarthCore's dumped wallet witnesses
    /// (WalletFlowTests with PRIVACY_TOML_OUT), proves every one through this
    /// prover and verifies it with the genesis-equal VK.
    func testWalletWitnesses() throws {
        guard let dir = ProcessInfo.processInfo.environment["PRIVACY_TOML_DIR"] else { throw XCTSkip("PRIVACY_TOML_DIR not set") }
        let root = try RepoLayout.root(from: #filePath)
        let circuits = root.appendingPathComponent("android/app/src/main/assets/circuits")
        var manifests: [PrivacyCircuitProver.Kind: Data] = [:]
        for k in PrivacyCircuitProver.Kind.allCases { manifests[k] = try Data(contentsOf: circuits.appendingPathComponent("\(k.rawValue).json")) }
        let prover = PrivacyCircuitProver(manifests: manifests)
        let files = try FileManager.default.contentsOfDirectory(atPath: dir).filter { $0.hasSuffix(".toml") }.sorted()
        XCTAssertFalse(files.isEmpty)
        for f in files {
            let kind: PrivacyCircuitProver.Kind = f.contains("_transfer_") ? .transfer : .membership
            let inputs = parseToml(try String(contentsOfFile: dir + "/" + f, encoding: .utf8))
            // The public inputs in the chain's order, from the witness itself.
            let keys = kind == .transfer
                ? ["root", "nf", "cm_out", "fee", "v_pub_out", "asset_pub", "signal"]
                : ["root", "scope", "nullifier", "signal", "excluded_dsc", "excluded_country", "max_activation"]
            let expected = keys.flatMap { k -> [String] in
                let v = inputs[k]!
                let xs = (v as? [String]) ?? [v as! String]
                return xs.map { x in
                    let h = x.hasPrefix("0x") ? String(x.dropFirst(2)) : hexFromDecimal(x)
                    return String(repeating: "0", count: 64 - h.count) + h
                }
            }
            let body = try prover.prove(kind, inputs: inputs, expected: expected)
            XCTAssertTrue(try prover.verify(kind, body: body, publicInputs: expected), f)
        }
    }
}
