import Foundation

/// BIP-39 mnemonic generation, validation, and seed derivation.
public enum BIP39 {

    public enum Error: Swift.Error, Equatable {
        case badWordCount(Int)
        case unknownWord(String)
        case badChecksum
        case badEntropyLength(Int)
    }

    /// A fresh phrase. 128 bits of entropy — twelve words, matching what the
    /// Android wallet generates, so a user sees the same shape on both.
    public static func generateMnemonic(strengthBits: Int = 128) throws -> String {
        guard strengthBits % 32 == 0, (128 ... 256).contains(strengthBits) else {
            throw Error.badEntropyLength(strengthBits)
        }
        var entropy = Data(repeating: 0, count: strengthBits / 8)
        let status = entropy.withUnsafeMutableBytes { buf in
            SecRandomCopyBytes(kSecRandomDefault, buf.count, buf.baseAddress!)
        }
        precondition(status == errSecSuccess, "SecRandomCopyBytes failed: \(status)")
        defer { entropy.resetBytes(in: 0 ..< entropy.count) }
        return try mnemonic(fromEntropy: entropy)
    }

    public static func mnemonic(fromEntropy entropy: Data) throws -> String {
        guard entropy.count % 4 == 0, (16 ... 32).contains(entropy.count) else {
            throw Error.badEntropyLength(entropy.count)
        }
        // Checksum is the first entropy-length/32 bits of SHA256(entropy),
        // appended to the entropy before the 11-bit split.
        let checksumBits = entropy.count * 8 / 32
        let hash = Hashes.sha256(entropy)

        var bits = [Bool]()
        bits.reserveCapacity(entropy.count * 8 + checksumBits)
        for byte in entropy {
            for i in (0 ..< 8).reversed() { bits.append((byte >> UInt8(i)) & 1 == 1) }
        }
        for i in 0 ..< checksumBits {
            bits.append((hash[i / 8] >> UInt8(7 - i % 8)) & 1 == 1)
        }

        var words = [String]()
        for chunk in stride(from: 0, to: bits.count, by: 11) {
            var idx = 0
            for i in 0 ..< 11 { idx = idx << 1 | (bits[chunk + i] ? 1 : 0) }
            words.append(BIP39Wordlist.english[idx])
        }
        return words.joined(separator: " ")
    }

    /// The entropy a phrase encodes, throwing if the checksum does not hold.
    public static func entropy(fromMnemonic mnemonic: String) throws -> Data {
        let words = normalize(mnemonic).split(separator: " ").map(String.init)
        guard [12, 15, 18, 21, 24].contains(words.count) else {
            throw Error.badWordCount(words.count)
        }

        var bits = [Bool]()
        bits.reserveCapacity(words.count * 11)
        for word in words {
            guard let idx = BIP39Wordlist.englishIndex[word.lowercased()] else {
                throw Error.unknownWord(word)
            }
            for i in (0 ..< 11).reversed() { bits.append((idx >> i) & 1 == 1) }
        }

        let entropyBits = bits.count * 32 / 33
        var entropy = Data(repeating: 0, count: entropyBits / 8)
        for i in 0 ..< entropyBits where bits[i] {
            entropy[i / 8] |= UInt8(1 << (7 - i % 8))
        }

        let hash = Hashes.sha256(entropy)
        for i in 0 ..< (bits.count - entropyBits) {
            let expected = (hash[i / 8] >> UInt8(7 - i % 8)) & 1 == 1
            guard bits[entropyBits + i] == expected else { throw Error.badChecksum }
        }
        return entropy
    }

    public static func isValid(mnemonic: String) -> Bool {
        (try? entropy(fromMnemonic: mnemonic)) != nil
    }

    /// The 64-byte seed. 2048 rounds of PBKDF2-HMAC-SHA512 over the phrase,
    /// salted with "mnemonic" + passphrase.
    ///
    /// Note this does *not* require a valid checksum, by design: BIP-39 seeds
    /// a phrase whether or not it validates, and refusing here would lock out
    /// a wallet restored from a phrase generated by a non-conforming tool.
    /// Validate separately, at the point where the user types it.
    public static func seed(fromMnemonic mnemonic: String, passphrase: String = "") -> Data {
        let password = Data(normalize(mnemonic).utf8)
        let salt = Data(("mnemonic" + passphrase).decomposedStringWithCompatibilityMapping.utf8)
        return Hashes.pbkdf2SHA512(password: password, salt: salt, rounds: 2048, keyLength: 64)
    }

    /// NFKD and single-spaced. The normalisation is what the spec requires;
    /// collapsing whitespace is what a pasted phrase needs.
    ///
    /// Deliberately *not* lowercased. Case changes the seed, and bitcoinj —
    /// which the Android wallet derives with — does not fold it either, so
    /// folding here would give the two platforms different addresses for the
    /// same typed phrase. Case is folded only when looking a word up in the
    /// list, where it decides validity rather than the key.
    private static func normalize(_ mnemonic: String) -> String {
        mnemonic
            .decomposedStringWithCompatibilityMapping
            .split(whereSeparator: { $0.isWhitespace })
            .joined(separator: " ")
    }
}
