[workspace]
members = [
  "poa_core",
  "privacy_core",
  "membership",
  "move",
  "action",
  "stake",
  "vote",
  "lean_poa_rsa2048_sha256",
  "lean_poa_rsa2048_sha1",
  "lean_poa_rsa2048_sha1_sha256_sha256",
  "lean_poa_rsa2048_sha256_sha1_sha1",
  "lean_poa_rsa2048_sha512_sha512_sha256",
  "lean_poa_rsa2048_sha512",
  "lean_poa_rsa3072_sha256",
  "lean_poa_rsa3072_sha1",
  "lean_poa_rsa4096_sha256",
  "lean_poa_rsa4096_sha1",
  "lean_poa_rsa4096_sha512_sha512_sha256",
  "lean_poa_rsa4096_sha512",
  "lean_poa_rsa2048_pss_sha256",
  "lean_poa_rsa2048_pss_sha384",
  "lean_poa_rsa2048_pss_sha512_sha512_sha256",
  "lean_poa_rsa2048_pss_sha512",
  "lean_poa_rsa3072_pss_sha256",
  "lean_poa_rsa3072_pss_sha384",
  "lean_poa_rsa4096_pss_sha256",
  "lean_poa_p224_sha256_sha224_sha224",
  "lean_poa_p224_sha256_sha256_sha224",
  "lean_poa_p256_sha256",
  "lean_poa_p256_sha1",
  "lean_poa_p384_sha256",
  "lean_poa_p384_sha384",
  "lean_poa_p521_sha512",
  "lean_poa_bp224_sha224",
  "lean_poa_bp224_sha1",
  "lean_poa_bp256_sha256",
  "lean_poa_bp384_sha256",
  "lean_poa_bp384_sha384",
  "lean_poa_bp512_sha384",
  "lean_poa_bp512_sha512",
]
